# https://tuto.grademe.fr/inception/

# mariadb:
#     my.cnf
#         sudo apt update
#         sudo apt upgrade
#         sudo apt install mariadb-server
#         cat /etc/mysql/mariadb.conf.d/50-server.cnf

#     Dockerfile
#         https://mariadb.com/kb/en/creating-a-custom-container-image/

# nginx:
#     nginx.conf
#         https://ubiq.co/tech-blog/nginx-ssl-configuration-step-step-details/
#         sudo apt install nginx
#         cat /etc/nginx/nginx.conf

#     Dockerfile
#         https://hub.docker.com/_/nginx

# wordpress:
#     wp-config.php
#         https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php
    
#     Dockerfile
#         https://hub.docker.com/_/wordpress
#         WP-CLI https://wp-cli.org/fr/

version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST: ${MYSQL_HOSTNAME}
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
    ports:
      - "8080:80"
    networks:
      - wordpress_network
    depends_on:
      - mariadb

networks:
  wordpress_network:
    driver: bridge

volumes:
  mariadb_data:
