# https://tuto.grademe.fr/inception/

# mariadb:
#     my.cnf
#         sudo apt update
#         sudo apt upgrade
#         sudo apt install mariadb-server
#         cat /etc/mysql/mariadb.conf.d/50-server.cnf

#     Dockerfile
#         https://mariadb.com/kb/en/creating-a-custom-container-image/

# nginx:
#     nginx.conf
#         https://ubiq.co/tech-blog/nginx-ssl-configuration-step-step-details/
#         sudo apt install nginx
#         cat /etc/nginx/nginx.conf

#     Dockerfile
#         https://hub.docker.com/_/nginx

# wordpress:
#     wp-config.php
#         https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php
    
#     Dockerfile
#         https://hub.docker.com/_/wordpress
#         WP-CLI https://wp-cli.org/fr/

version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
        - CERTS_CRT
        - CERTS_KEY
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      args:
        - WORDPRESS_DB_HOST
        - WORDPRESS_DB_NAME
        - WORDPRESS_URL
        - WORDPRESS_GUEST_USER
        - WORDPRESS_GUEST_PASSWORD
        - WORDPRESS_DB_USER
        - WORDPRESS_DB_PASSWORD
        - WORDPRESS_ADMIN_USER
        - WORDPRESS_ADMIN_PASSWORD
        - WORDPRESS_ADMIN_EMAIL
    depends_on:
      - mariadb
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql/
    restart: always
    networks:
      - inception

volumes:
  mariadb_volume:
    external: true
  wordpress_volume:
    external: true

networks:
  inception:
    driver: bridge